from agents import Runner
from .research_agent import research_agent
from .summary_agent import summary_agent
from .email_agent import email_agent

from agents import Runner
from .research_agent import research_agent
from .summary_agent import summary_agent
from .email_agent import email_agent

async def run_multi_agent_pipeline(user_input: str) -> str:
    """
    Orchestrates the multi-agent pipeline based on user request keywords.
    Delegates tasks to specific agents and handles the data flow between them.
    
    Args:
        user_input (str): The task description from the user.
        
    Returns:
        str: The final output generated by the last agent in the pipeline.
    """
    task = user_input.lower()
    results = {}
    
    print("\n" + "="*50)
    print(f"[*] Pipeline Started for task: '{user_input}'")
    print("="*50)
    
    # --- Stage 1: Research ---
    # Every workflow requires a foundational research step.
    print("[>>] ResearchAgent: Gathering data...")
    research_result = await Runner.run(research_agent, user_input)
    results['research'] = research_result.final_output
    print("[✓] ResearchAgent: Completed.")
    
    # Return early if research is the only request.
    if "research" in task and "summary" not in task and "email" not in task:
        print("[*] Pipeline Finished (Returning Research)\n")
        return results['research']

    # --- Stage 2: Summary ---
    # Summarize research if summary or email is requested.
    if "summary" in task or "email" in task:
        print("[>>] SummaryAgent: Summarizing content...")
        summary_result = await Runner.run(summary_agent, results['research'])
        results['summary'] = summary_result.final_output
        print("[✓] SummaryAgent: Completed.")
        
        # Return early if summary is the final request.
        if "summary" in task and "email" not in task:
            print("[*] Pipeline Finished (Returning Summary)\n")
            return results['summary']

    # --- Stage 3: Email ---
    # Draft email if email is explicitly requested.
    if "email" in task:
        print("[>>] EmailAgent: Drafting email...")
        email_result = await Runner.run(email_agent, results['summary'])
        results['email'] = email_result.final_output
        print("[✓] EmailAgent: Completed.")
        print("[*] Pipeline Finished (Returning Email)\n")
        return results['email']

    # Default fallback to research results.
    print("[*] Pipeline Finished (Default: Research)\n")
    return results['research']
